# Site settings
title: Hobbzey.com
description: 'A Nitfy Little Tag-Line'
url: 'http://hobbzey.com'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Hobbzey'
  email: hobbzey@gmail.com
  twitter_username: hobbzey
  facebook_username: hobbzey
  github_username:  hobbzey
  linkedin_username:  hobbzey

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
